name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  rust_msrv: "1.77.1"

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.6.0

      - name: Install cargo-sort
        run: make install-cargo-sort

      - name: Install taplo-cli
        run: make install-taplo-cli

      - name: Cargo format
        run: make check-fmt

      - name: Check diff
        run: git diff --exit-code

      - name: Cargo clippy
        run: make check-clippy

      - name: Cargo sort
        run: make cargo-sort

      - name: Cargo Machete
        run: make cargo-machete

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-builder
        with:
          rust-version: ${{ env.rust_msrv }}

      - name: Build
        run: make build

  build_with_no_default_features:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build -p iceberg --no-default-features

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-builder
        with:
          rust-version: ${{ env.rust_msrv }}

      - name: Test
        run: cargo test --no-fail-fast --all-targets --all-features --workspace

      - name: Async-std Test
        run: cargo test --no-fail-fast --all-targets --no-default-features  --features "async-std" --features "storage-fs" --workspace

      - name: Doc Test
        run: cargo test --no-fail-fast --doc --all-features --workspace
