# name: Publish

# on:
#   push:
#     tags:
#       - '*'
#   workflow_dispatch:

# env:
#   rust_msrv: "1.77.1"

# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     strategy:
#       # Publish package one by one instead of flooding the registry
#       max-parallel: 1
#       matrix:
#         # Order here is sensitive, as it will be used to determine the order of publishing
#         package:
#           - "crates/iceberg"
#           - "crates/catalog/hms"
#           - "crates/catalog/rest"
#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup Rust toolchain
#         uses: ./.github/actions/setup-builder
#         with:
#           rust-version: ${{ env.rust_msrv }}

#       - name: Publish ${{ matrix.package }}
#         working-directory: ${{ matrix.package }}
#         # Only publish if it's a tag and the tag is not a pre-release
#         if: ${{ startsWith(github.ref, 'refs/tags/') && !contains(github.ref, '-') }}
#         run: cargo publish --all-features
#         env:
#           CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}