# name: Website

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
#   cancel-in-progress: true

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup mdBook
#         uses: peaceiris/actions-mdbook@v2
#         with:
#           mdbook-version: '0.4.36'

#       - name: Build
#         working-directory: website
#         run: mdbook build

#       - name: Copy asf file
#         run: cp .asf.yaml ./website/book/.asf.yaml

#       - name: Build API docs
#         run: |
#           cargo doc --no-deps --workspace --all-features
#           cp -r target/doc ./website/book/api

#       - name: Deploy to gh-pages
#         uses: peaceiris/actions-gh-pages@v4.0.0
#         if: github.event_name == 'push' && github.ref_name == 'main'
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: website/book
#           publish_branch: gh-pages
